apiVersion: v1
kind: Service
metadata:
  name: pulsar
spec:
  ports:
    - name: pulsar
      port: 6650
    - name: admin
      port: 8080
  clusterIP: None
  # type: ClusterIP
  selector:
    app: pulsar
    release: pulsar
---
apiVersion: v1
kind: Service
metadata:
  name: pulsarnp
spec:
  ports:
    - name: httpadmin
      port: 8080
      nodePort: 30081
  type: NodePort
  selector:
    app: pulsar
    release: pulsar
