apiVersion: apps/v1
kind: StatefulSet
metadata:
  name:  etcd
spec:
  selector:
    matchLabels:
      app:  etcd
      release:  etcd
  serviceName:  etcd
  replicas: 1
  template:
    metadata:
      labels:
        app:  etcd
        release:  etcd
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name:  etcd
        image: quay.io/coreos/etcd:v3.5.4
        imagePullPolicy: IfNotPresent
        command: ["sh","-c"]
        # command: ["sh","-c","etcd","-name","etcd1","--data-dir","/etcd-data","-advertise-client-urls","http://0.0.0.0:2279","-listen-client-urls","http://0.0.0.0:2279","-listen-peer-urls","http://0.0.0.0:2280"]
        args: ["etcd -name etcd --data-dir /etcd-data -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380"]
        ports:
        - name:  etcd
          containerPort: 2279
      # volumes:
      # - name: configfile
      #   configMap:
      #     name:   etcd

# ./etcd --name etcd1 --advertise-client-urls http://0.0.0.0:2379 --listen-client-urls http://0.0.0.0:2379 --listen-peer-urls http://0.0.0.0:2380