apiVersion: batch/v1
kind: Job
metadata:
  name: pulsar-init
spec:
  template:
    spec:
      containers:
      - name: pulsar
        image: apachepulsar/pulsar:2.10.0
        imagePullPolicy: IfNotPresent
        command: ["sh","-c"]
        args: [" bin/pulsar initialize-cluster-metadata -c smartoilets -uw http://etcd:8080 -cms etcd://etcd:2379 -md etcd://etcd:2379"]
      restartPolicy: Never
  backoffLimit: 4

