apiVersion: v1
kind: ServiceAccount
metadata:
  name: pulsar
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pulsar
  
rules:
- apiGroups:
  - "batch"
  resources:
  - jobs
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pulsar
rules:
- apiGroups:
  - "*"
  resources:
  - jobs
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pulsar
  
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pulsar
subjects:
- kind: ServiceAccount
  name: pulsar
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pulsar
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pulsar
subjects:
- kind: ServiceAccount
  name: pulsar
  namespace: default
---